export const metadata = {
  title: 'Alpha Image Engine',
  description: 'Generated by Alpha Trading Lab',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
